app = "wgtodobot"

[env]
PORT = "10000"  # Match the port your app is actually using

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
