app = "wgtodobot"
primary_region = "sin" # Pastikan ini adalah region yang kamu inginkan

[env]
PORT = "8080"
PYTHON_VERSION = "3.10.x" # Menjamin konsistensi dengan Dockerfile

[processes]
web = "python bot.py" # Langsung menjalankan bot.py karena sudah ada webhook server internal

[[services]]
processes = ["web"]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.ports]]
  port = 80
  handlers = ["http"]
