# === FILE: fly.toml ===
app = "wgtodobot"
primary_region = "sin"  # Ubah region kalau mau

[env]
  PYTHON_VERSION = "3.9.x"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  # Gunakan proses tunggal karena pakai webhook bawaan PTB
  app = "python bot.py"
